export const REPO_URL = 'https://dl.friendlyhub.org/repo/';
export const REPO_NAME = 'friendlyhub';
export const FLATPAKREPO_URL = `${REPO_URL}friendlyhub.flatpakrepo`;

/** URL for the .flatpakref file (served from CDN, generated by flat-manager on publish). */
export function flatpakrefUrl(appId: string): string {
  return `${REPO_URL}appstream/${appId}.flatpakref`;
}

/** flatpak+https:// URI that triggers GNOME Software / KDE Discover directly. */
export function flatpakInstallUrl(appId: string): string {
  return `flatpak+https://dl.friendlyhub.org/repo/appstream/${appId}.flatpakref`;
}
